import json
import os

p = 'energy_project.ipynb'
nb = json.load(open(p, 'r', encoding='utf-8'))
found = False

new_source = [
    "from pyspark.sql import functions as F\n",
    "import json\n",
    "import uuid\n",
    "import os\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from IPython.display import HTML, display\n",
    "\n",
    "try:\n",
    "    plt.style.use(\"seaborn-v0_8-whitegrid\")\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "def safe_int(col):\n",
    "    s = F.trim(col.cast(\"string\"))\n",
    "    return F.when(s.rlike(\"^[0-9]+$\"), s.cast(\"int\")).otherwise(F.lit(None).cast(\"int\"))\n",
    "\n",
    "def safe_float(col):\n",
    "    s = F.trim(col.cast(\"string\"))\n",
    "    return F.when(s.rlike(\"^[0-9.]+\$\"), s.cast(\"float\")).otherwise(F.lit(None).cast(\"float\"))\n",
    "\n",
    "def connection_status_expr(col_name: str):\n",
    "    c = F.col(col_name) if isinstance(col_name, str) else col_name\n",
    "    return (\n",
    "        F.when(c == 1, F.lit(\"Connected\"))\n",
    "        .when(c == 2, F.lit(\"Not connected\"))\n",
    "        .otherwise(F.lit(\"Unknown/NA\"))\n",
    "    )\n",
    "\n",
    "CONNECTED_COL = \"Is your household connected to the National or Local Mini-Grid?\"\n",
    "plots_root = os.path.join(\"etl_output\", \"plots\")\n",
    "jpg_dir = os.path.join(plots_root, \"jpg\")\n",
    "os.makedirs(jpg_dir, exist_ok=True)\n",
    "\n",
    "def _save_fig(fig, name: str):\n",
    "    jpg_path = os.path.join(jpg_dir, f\"{name}.jpg\")\n",
    "    try:\n",
    "        fig.patch.set_facecolor(\"white\")\n",
    "    except Exception:\n",
    "        pass\n",
    "    fig.savefig(jpg_path, dpi=180, bbox_inches=\"tight\", facecolor=\"white\")\n",
    "    print(\"Saved:\", jpg_path)\n",
    "\n",
    "def _clean_labels(dfp: pd.DataFrame, key: str, also_drop: set | None = None) -> pd.DataFrame:\n",
    "    if dfp.empty:\n",
    "        return dfp\n",
    "    s = dfp[key].astype(str).str.strip()\n",
    "    mask = s.ne(\"\") & s.str.upper().ne(\"UNKNOWN\")\n",
    "    if also_drop:\n",
    "        mask = mask & ~s.isin(also_drop)\n",
    "    return dfp.loc[mask].copy()\n",
    "\n",
    "def _barh(values, label_key: str, value_key: str, title: str, filename: str):\n",
    "    if not values:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame(values)\n",
    "    dfp = _clean_labels(dfp, label_key)\n",
    "    if dfp.empty:\n",
    "        print(\"No non-empty labels for\", filename)\n",
    "        return\n",
    "    dfp = dfp.sort_values(value_key, ascending=True)\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    ax.barh(dfp[label_key], dfp[value_key], color=\"#2563eb\")\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(value_key)\n",
    "    ax.set_ylabel(label_key)\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _pie(values, label_key: str, value_key: str, title: str, filename: str):\n",
    "    if not values:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame(values)\n",
    "    dfp = _clean_labels(dfp, label_key)\n",
    "    if dfp.empty:\n",
    "        print(\"No non-empty labels for\", filename)\n",
    "        return\n",
    "    fig, ax = plt.subplots(figsize=(7, 7))\n",
    "    ax.pie(dfp[value_key], labels=dfp[label_key], autopct='%1.1f%%', startangle=140, colors=[\"#3b82f6\", \"#ef4444\", \"#10b981\", \"#f59e0b\"])\n",
    "    ax.set_title(title)\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _stacked_bar(values, category_key: str, series_key: str, value_key: str, title: str, filename: str):\n",
    "    if not values:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame(values)\n",
    "    dfp = _clean_labels(dfp, category_key)\n",
    "    if dfp.empty:\n",
    "        print(\"No non-empty labels for\", filename)\n",
    "        return\n",
    "    pivot_df = dfp.pivot(index=category_key, columns=series_key, values=value_key).fillna(0)\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    pivot_df.plot(kind=\"bar\", stacked=True, ax=ax, color=[\"#3b82f6\", \"#ef4444\", \"#10b981\", \"#f59e0b\"])\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(category_key)\n",
    "    ax.set_ylabel(value_key)\n",
    "    ax.legend(title=series_key)\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _perf_lines(values, x_key: str, y_key: str, series_key: str, title: str, filename: str):\n",
    "    if not values:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame(values)\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    for label, group in dfp.groupby(series_key):\n",
    "        group = group.sort_values(x_key)\n",
    "        ax.plot(group[x_key], group[y_key], marker='o', label=label)\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(x_key)\n",
    "    ax.set_ylabel(y_key)\n",
    "    ax.legend()\n",
    "    ax.grid(True, alpha=0.3)\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _top_counts(df_in, col_name: str, out_key: str, n: int = 10, extra_filter=None):\n",
    "    if col_name not in df_in.columns:\n",
    "        return []\n",
    "    base = df_in.select(F.trim(F.col(col_name).cast(\"string\")).alias(out_key)).filter(F.col(out_key).isNotNull() & (F.col(out_key) != \"\") & (F.upper(F.col(out_key)) != \"UNKNOWN\"))\n",
    "    if extra_filter is not None:\n",
    "        base = base.filter(extra_filter)\n",
    "    rows = base.groupBy(out_key).count().orderBy(F.desc(\"count\")).limit(int(n)).collect()\n",
    "    return [{out_key: r[out_key], \"count\": int(r[\"count\"])} for r in rows]\n",
    "\n",
    "def _connection_by_category(df_in, category_col: str, n: int = 10):\n",
    "    if category_col not in df_in.columns:\n",
    "        return []\n",
    "    tmp = (\n",
    "        df_in\n",
    "        .select(\n",
    "            F.trim(F.col(category_col).cast(\"string\")).alias(\"category\"),\n",
    "            safe_int(F.col(CONNECTED_COL)).alias(\"connected_to_grid\"),\n",
    "        )\n",
    "        .filter(F.col(\"category\").isNotNull() & (F.col(\"category\") != \"\") & (F.upper(F.col(\"category\")) != \"UNKNOWN\") & F.col(\"connected_to_grid\").isNotNull())\n",
    "        .withColumn(\"connection_status\", connection_status_expr(\"connected_to_grid\"))\n",
    "        .filter(F.col(\"connection_status\") != \"Unknown/NA\")\n",
    "    )\n",
    "    top = tmp.groupBy(\"category\").count().orderBy(F.desc(\"count\")).limit(int(n)).select(\"category\")\n",
    "    rows = tmp.groupBy(\"category\", \"connection_status\").count().join(top, on=\"category\", how=\"inner\").collect()\n",
    "    return [{\"category\": r[\"category\"], \"connection_status\": r[\"connection_status\"], \"count\": int(r[\"count\"])} for r in rows]\n",
    "\n",
    "def _hist_numeric(df_in, col_name: str, title: str, filename: str, sample_n: int = 6000, bins: int = 18):\n",
    "    if col_name not in df_in.columns:\n",
    "        print(\"Column missing:\", col_name)\n",
    "        return\n",
    "    vals = df_in.select(safe_float(F.col(col_name)).alias(\"v\")).filter(F.col(\"v\").isNotNull()).limit(int(sample_n)).toPandas()[\"v\"]\n",
    "    if len(vals) == 0:\n",
    "        print(\"No numeric data for\", filename)\n",
    "        return\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    ax.hist(vals, bins=int(bins), color=\"#16a34a\", edgecolor=\"white\")\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(col_name)\n",
    "    ax.set_ylabel(\"Count\")\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _connection_rate_bar(df_in, category_col: str, title: str, filename: str, n: int = 10):\n",
    "    if category_col not in df_in.columns:\n",
    "        print(\"Column missing:\", category_col)\n",
    "        return\n",
    "    tmp = (\n",
    "        df_in\n",
    "        .select(\n",
    "            F.trim(F.col(category_col).cast(\"string\")).alias(\"category\"),\n",
    "            safe_int(F.col(CONNECTED_COL)).alias(\"connected_to_grid\"),\n",
    "        )\n",
    "        .filter(F.col(\"category\").isNotNull() & (F.col(\"category\") != \"\") & (F.upper(F.col(\"category\")) != \"UNKNOWN\") & F.col(\"connected_to_grid\").isNotNull())\n",
    "        .withColumn(\"connection_status\", connection_status_expr(\"connected_to_grid\"))\n",
    "        .filter(F.col(\"connection_status\") != \"Unknown/NA\")\n",
    "    )\n",
    "    agg = (\n",
    "        tmp.groupBy(\"category\")\n",
    "        .agg(\n",
    "            F.count(F.lit(1)).alias(\"total\"),\n",
    "            F.sum(F.when(F.col(\"connection_status\") == \"Connected\", F.lit(1)).otherwise(F.lit(0))).alias(\"connected\"),\n",
    "        )\n",
    "        .withColumn(\"pct_connected\", (F.col(\"connected\") / F.col(\"total\")) * 100)\n",
    "        .orderBy(F.desc(\"total\"))\n",
    "        .limit(int(n))\n",
    "        .collect()\n",
    "    )\n",
    "    if not agg:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame([r.asDict() for r in agg]).sort_values(\"pct_connected\", ascending=True)\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    ax.barh(dfp[\"category\"], dfp[\"pct_connected\"], color=\"#f59e0b\")\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(\"% Connected\")\n",
    "    ax.set_ylabel(category_col)\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _numeric_boxplot_by_status(df_in, numeric_col: str, title: str, filename: str, sample_n: int = 7000):\n",
    "    if numeric_col not in df_in.columns:\n",
    "        print(\"Column missing:\", numeric_col)\n",
    "        return\n",
    "    dfp = (\n",
    "        df_in.select(\n",
    "            safe_float(F.col(numeric_col)).alias(\"val\"),\n",
    "            connection_status_expr(CONNECTED_COL).alias(\"status\")\n",
    "        )\n",
    "        .filter(F.col(\"val\").isNotNull() & (F.col(\"status\") != \"Unknown/NA\"))\n",
    "        .limit(int(sample_n))\n",
    "        .toPandas()\n",
    "    )\n",
    "    if dfp.empty:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    dfp.boxplot(column=\"val\", by=\"status\", ax=ax, grid=False)\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(\"Connection Status\")\n",
    "    ax.set_ylabel(numeric_col)\n",
    "    fig.suptitle(\"\")\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _scatter_by_status(df_in, x_col: str, y_col: str, title: str, filename: str, sample_n: int = 7000):\n",
    "    if x_col not in df_in.columns or y_col not in df_in.columns:\n",
    "        print(\"Column(s) missing\")\n",
    "        return\n",
    "    dfp = (\n",
    "        df_in.select(\n",
    "            safe_float(F.col(x_col)).alias(\"x\"),\n",
    "            safe_float(F.col(y_col)).alias(\"y\"),\n",
    "            connection_status_expr(CONNECTED_COL).alias(\"status\")\n",
    "        )\n",
    "        .filter(F.col(\"x\").isNotNull() & F.col(\"y\").isNotNull() & (F.col(\"status\") != \"Unknown/NA\"))\n",
    "        .limit(int(sample_n))\n",
    "        .toPandas()\n",
    "    )\n",
    "    if dfp.empty:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    fig, ax = plt.subplots(figsize=(9, 5))\n",
    "    for status, group in dfp.groupby(\"status\"):\n",
    "        ax.scatter(group[\"x\"], group[\"y\"], label=status, alpha=0.5, s=20)\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(x_col)\n",
    "    ax.set_ylabel(y_col)\n",
    "    ax.legend()\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "def _heatmap_connection_rate(df_in, row_col: str, col_col: str, title: str, filename: str, row_n: int = 10, col_n: int = 6):\n",
    "    if row_col not in df_in.columns or col_col not in df_in.columns:\n",
    "        print(\"Column(s) missing\")\n",
    "        return\n",
    "    tmp = (\n",
    "        df_in.select(\n",
    "            F.trim(F.col(row_col).cast(\"string\")).alias(\"row\"),\n",
    "            F.trim(F.col(col_col).cast(\"string\")).alias(\"col\"),\n",
    "            safe_int(F.col(CONNECTED_COL)).alias(\"connected_to_grid\")\n",
    "        )\n",
    "        .filter(\n",
    "            F.col(\"row\").isNotNull() & (F.col(\"row\") != \"\") & (F.upper(F.col(\"row\")) != \"UNKNOWN\") &\n",
    "            F.col(\"col\").isNotNull() & (F.col(\"col\") != \"\") & (F.upper(F.col(\"col\")) != \"UNKNOWN\") &\n",
    "            F.col(\"connected_to_grid\").isNotNull()\n",
    "        )\n",
    "        .withColumn(\"status\", connection_status_expr(\"connected_to_grid\"))\n",
    "        .filter(F.col(\"status\") != \"Unknown/NA\")\n",
    "    )\n",
    "    top_rows = tmp.groupBy(\"row\").count().orderBy(F.desc(\"count\")).limit(int(row_n)).select(\"row\")\n",
    "    top_cols = tmp.groupBy(\"col\").count().orderBy(F.desc(\"count\")).limit(int(col_n)).select(\"col\")\n",
    "    filtered = tmp.join(top_rows, on=\"row\").join(top_cols, on=\"col\")\n",
    "    agg = (\n",
    "        filtered.groupBy(\"row\", \"col\")\n",
    "        .agg(\n",
    "            F.count(F.lit(1)).alias(\"total\"),\n",
    "            F.sum(F.when(F.col(\"status\") == \"Connected\", F.lit(1)).otherwise(F.lit(0))).alias(\"connected\")\n",
    "        )\n",
    "        .withColumn(\"pct\", (F.col(\"connected\") / F.col(\"total\")) * 100)\n",
    "        .collect()\n",
    "    )\n",
    "    if not agg:\n",
    "        print(\"No data for\", filename)\n",
    "        return\n",
    "    dfp = pd.DataFrame([r.asDict() for r in agg])\n",
    "    mat = dfp.pivot(index=\"row\", columns=\"col\", values=\"pct\").fillna(0)\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    im = ax.imshow(mat, cmap=\"YlGnBu\", aspect=\"auto\")\n",
    "    ax.set_title(title)\n",
    "    ax.set_xlabel(col_col)\n",
    "    ax.set_ylabel(row_col)\n",
    "    ax.set_xticks(range(len(mat.columns)))\n",
    "    ax.set_xticklabels([str(x) for x in mat.columns], rotation=35, ha=\"right\")\n",
    "    ax.set_yticks(range(len(mat.index)))\n",
    "    ax.set_yticklabels([str(x) for x in mat.index])\n",
    "    fig.colorbar(im, ax=ax, label=\"% Connected\")\n",
    "    fig.tight_layout()\n",
    "    _save_fig(fig, filename)\n",
    "    plt.show()\n",
    "\n",
    "top_n = 10\n",
    "region_connected_top = (\n",
    "    df_etl\n",
    "    .withColumn(\"connection_status\", connection_status_expr(\"connected_to_grid\"))\n",
    "    .filter((F.col(\"connection_status\") == \"Connected\") & (F.col(\"region\") != \"UNKNOWN\") & (F.trim(F.col(\"region\")) != \"\"))\n",
    "    .groupBy(\"region\")\n",
    "    .count()\n",
    "    .orderBy(F.desc(\"count\"))\n",
    "    .limit(top_n)\n",
    ")\n"
]

for c in nb['cells']:
    src = ''.join(c.get('source', []))
    if 'region_connected_top =' in src and 'df_etl' in src and 'def connection_status_expr' in src:
        c['source'] = new_source
        found = True
        break

if found:
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)
    print('Successfully updated Code Cell 13')
else:
    print('Could not find Code Cell 13 to update')
